### ISSUE TITLE
[BUG]  java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1

### ISSUE THREAD

**Issue by cmd0129** [codekidX/storage-chooser#119]
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$5$1.run(SecondaryChooserFragment.java:154)

**Comment by codekidX** [comment]
Hello, this bug should be fixed in 3.0 release. But as far as the release date is concerned, it is still unknown due to the new SAF restriction.

**Comment by EbrahimElsify** [comment]
when will closed
