### ISSUE TITLE
[BUG] Crash on launchng dialog on Android 11

### ISSUE THREAD

**Issue by omkar-tenkale** [codekidX/storage-chooser#133]
**Describe the bug**
App crashes when picker  is launched with following code

**To Reproduce**
 ```
 StorageChooser.Theme theme = new StorageChooser.Theme(SettingsActivity.this.getApplicationContext());
        int[] myScheme = theme.getDefaultScheme();

        myScheme[StorageChooser.Theme.OVERVIEW_HEADER_INDEX] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);
        myScheme[StorageChooser.Theme.SEC_ADDRESS_BAR_BG] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);
        myScheme[StorageChooser.Theme.SEC_FOLDER_TINT_INDEX] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);
        myScheme[StorageChooser.Theme.SEC_SELECT_LABEL_INDEX] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);
        myScheme[StorageChooser.Theme.SEC_FOLDER_CREATION_BG_INDEX] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);
        myScheme[StorageChooser.Theme.OVERVIEW_MEMORYBAR_INDEX] = SettingsActivity.this.getResources().getColor(R.color.colorBlue);

        theme.setScheme(myScheme);

        final StorageChooser.Builder builder = new StorageChooser.Builder();
        final StorageChooser chooser = builder
                .withActivity((Activity) SettingsActivity.this)
                .withFragmentManager((SettingsActivity.this).getFragmentManager())
                .allowAddFolder(true)
                .hideFreeSpaceLabel(true)
                .showHidden(true)
                .withMemoryBar(false)
                .setListTypeface("font/GlacialIndifference-Regular.otf", true)
                .setHeadingTypeface("font/GlacialIndifference-Regular.otf", true)
                .setTheme(theme)
                .build();

        chooser.show();
```

**Expected behavior**
It should show picker dialog as usual

**Smartphone (please complete the following information):**
 - OS: Android 11

**Additional context**
Stack Trace
```

 java.lang.NullPointerException: Attempt to get length of null array
        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:261)
        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:114)
        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:84)
        at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:299)
        at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:417)
        at android.app.Fragment.performGetLayoutInflater(Fragment.java:1322)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by omkar-tenkale** [comment]
Same as #127 

Closing this one
