### ISSUE TITLE
Reduce minSdkVersion to API 9

### ISSUE THREAD

**Issue by fennifith** [codekidX/storage-chooser#24]
This will probably require some slightly more significant changes to how the library works instead of just modifying the layout files. When tested on 10, I got a NullPonterException at ChooserDialogFragment.populateList(ChooserDialogFragment.java:261). This could be for a few different reasons, but I'll look at it more closely later this week.

**Comment by codekidX** [comment]
Hmm ... my be the file hierarchy was different at that time. Like,` storage/emulated` was actually `sdcard0` or somewhat similar bug. 🤔 I'll have to dig through some Genymotion with sdk 10.

**Comment by pzienowicz** [comment]
The same issue, when trying on Android 4.1.1.
If I want to show chooser with overview - I see:
` java.lang.NullPointerException
                                                     at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:260)
                                                     at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:114)
                                                     at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:84)
                                                     at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:298)
                                                     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)`

When overview is skipped - it works, but I have two memory slots and only first is loaded.

**Comment by pzienowicz** [comment]
Closed because?
It is fixed? I don't see any commit for that.
