### ISSUE TITLE
Issue: android.view.InflateException: Binary XML file line #17: Error inflating class TextView

### ISSUE THREAD

**Issue by ryust** [codekidX/storage-chooser#30]
When including the storage-chooser library in my app, Google Play gives the following error during its pre-launch test on various devices. The Samsung S6 on Android 5.1 produces the following stack trace:

FATAL EXCEPTION: main
 Process: com.mobiltal.geoohLive, PID: 24193
 android.view.InflateException: Binary XML file line #17: Error inflating class TextView
 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
 	at android.widget.Editor.showError(Editor.java:433)
 	at android.widget.Editor.setError(Editor.java:474)
 	at android.widget.TextView.setError(TextView.java:5542)
 	at android.widget.TextView.setError(TextView.java:5527)
 	at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.validateFolderName(SecondaryChooserFragment.java:525)
 	at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.access$600(SecondaryChooserFragment.java:49)
 	at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$5.onClick(SecondaryChooserFragment.java:130)
 	at android.view.View.performClick(View.java:5254)
 	at android.view.View$PerformClick.run(View.java:21173)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:145)
 	at android.app.ActivityThread.main(ActivityThread.java:6837)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
 Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 24
 	at android.content.res.TypedArray.getColor(TypedArray.java:403)
 	at android.widget.TextView.<init>(TextView.java:1105)
 	at android.widget.TextView.<init>(TextView.java:1017)
 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
 	... 20 more

**Comment by codekidX** [comment]
Thanks for reporting. You can add `com.github.codekidX:storage-chooser:d4e9d6e ` inside your app:build.gradle until 1.0.35 is released 😄
