### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Invalid path: /storage/container

### ISSUE THREAD

**Issue by filol** [codekidX/storage-chooser#43]
One of my users causes this error when I use your library : 

Link : http://crashes.to/s/50412a88afe

`Fatal Exception: java.lang.IllegalArgumentException: Invalid path: /storage/container
       at android.os.StatFs.doStat(StatFs.java:46)
       at android.os.StatFs.(StatFs.java)
       at com.codekidlabs.storagechooser.utils.MemoryUtil.getTotalMemorySize(MemoryUtil.java:71)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:237)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:98)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:81)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:250)
       at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.BackStackRecord.run(BackStackRecord.java:684)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5679)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by libcore.io.ErrnoException: statvfs failed: EACCES (Permission denied)
       at libcore.io.Posix.statvfs(Posix.java)
       at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:132)
       at android.os.StatFs.doStat(StatFs.java:44)
       at android.os.StatFs.(StatFs.java)
       at com.codekidlabs.storagechooser.utils.MemoryUtil.getTotalMemorySize(MemoryUtil.java:71)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:237)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:98)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:81)
       at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:250)
       at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.BackStackRecord.run(BackStackRecord.java:684)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5679)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by codekidX** [comment]
Thanks for reporting. I have added a read access check on storage click.

**Comment by filol** [comment]
Hey ! My user got the same issue after i upgrade your library to 2.0. This issue isn't fixed ! You can check the stacktrace with the same link

**Comment by codekidX** [comment]
Are you in contact with the user? Let me know if `/storage/container` is an external storage or read-only system storage that he's trying to access it all the time.

I can't write an exception for this path until I know about this.

**Comment by filol** [comment]
Yes i'm contact with the user.
It looks like a system folder where has link to a system folder but apparently it is empty. My user deleted it but it needed root rights to do so. This has solved this problem but since it crashes with another errors: http://crashes.to/s/5b548bbaf56
I have tested it personally, it works very well for android 5+ but not for android 4.4. Is your libraries compatible with android 4.4?
