### ISSUE TITLE
selecting a file in /emulated/0/download folder 

### ISSUE THREAD

**Issue by codekidX** [codekidX/storage-chooser#45]
Same issue **_when just trying to select a file_**  on Genymotion AND My LG V20 actual device  after selecting a file in /emulated/0/download folder  

`   java.lang.NullPointerException: Attempt to invoke interface method 'void com.codekidlabs.storagechooser.StorageChooser$OnSelectListener.onSelect(java.lang.String)' on a null object reference
                                                                               at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$7$1.run(SecondaryChooserFragment.java:369)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)  `

**Comment by codekidX** [comment]
@mikecoppola16 your issue is moved here since it had no link with the issue you created before.

Can you tell me which version of library you are using ?

**Comment by codekidX** [comment]
closing this issue due to inactivity. Please reopen this issue whenever you have time to revert. Thanks for the issue.
