### ISSUE TITLE
 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by nestoleh** [codekidX/storage-chooser#56]
The error happened when I rotate device with open dialog "Choose storage" and pick any storage.
Chooser configuration
`new StorageChooser.Builder()
                    .withActivity(this)
                    .withFragmentManager(getFragmentManager())
                    .withMemoryBar(true)
                    .allowCustomPath(true)
                    .setType(StorageChooser.FILE_PICKER)
                    .shouldResumeSession(false)
                    .build();
`
Also if choose storage and rotate device I see next 
![image](https://user-images.githubusercontent.com/10635470/30267610-ca6a1aa4-96eb-11e7-9d26-bb1fe1cb10a0.png)

Full error:
`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                          at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1328)
                                                                          at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1346)
                                                                          at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
                                                                          at android.app.BackStackRecord.commit(BackStackRecord.java:705)
                                                                          at android.app.DialogFragment.show(DialogFragment.java:230)
                                                                          at com.codekidlabs.storagechooser.utils.DiskUtil.showSecondaryChooser(DiskUtil.java:67)
                                                                          at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment$1$1.run(ChooserDialogFragment.java:130)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by nestoleh** [comment]
This error also happening in demo application

**Comment by codekidX** [comment]
Hi, nice catch !! Add this changes to your calling Activity.

Regards.
