### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION:

### ISSUE THREAD

**Issue by NileshEvonix** [codekidX/storage-chooser#59]
Its throws exception after i select internal / external storage in my Samsung SM-G360H 
Android version 4.4.4 please fix this ASAP

FATAL EXCEPTION: main
                                               
                                                                 android.view.InflateException: Binary XML file line #85: Error inflating class <unknown>
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:627)
                                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329)
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693)
                                                                     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:601)
                                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:762) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:771) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:499) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
                                                                     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
                                                                     at android.os.Handler.handleCallback(Handler.java:733) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5433) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0200ee a=-1 r=0x7f0200ee}
                                                                     at android.content.res.Resources.loadDrawable(Resources.java:3423)
                                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:614)
                                                                     at android.widget.AbsListView.<init>(AbsListView.java:834)
                                                                     at android.widget.ListView.<init>(ListView.java:152)
                                                                     at android.widget.ListView.<init>(ListView.java:148)
                                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:601) 
                                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:762) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:771) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:499) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
                                                                     at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
                                                                     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
                                                                     at android.os.Handler.handleCallback(Handler.java:733) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5433) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by SAFatemi** [comment]
Salam.
I'm using version 2.0.3 and this exception already exists!!!
