### ISSUE TITLE
App crashes by no view found exception

### ISSUE THREAD

**Issue by shelake-chetan** [codekidX/storage-chooser#64]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.atlasso/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f100125 (com.atlasso:id/container) for fragment MediaPickerFragment{37d7bfb #0 id=0x7f100125 MediaPickerFragment}
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2607)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2701)
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                               at android.os.Looper.loop(Looper.java:207)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5789)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:739)
                                                            Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f100125 (com.atlasso:id/container) for fragment MediaPickerFragment{37d7bfb #0 id=0x7f100125 MediaPickerFragment}
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1413)
                                                               at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                               at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                               at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                               at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                               at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                               at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                               at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                               at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                               at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
                                                               at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                               at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
                                                               at android.app.Activity.performStart(Activity.java:6286)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2555)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2701) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5789) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:739)

**Comment by codekidX** [comment]
This is fixed but not released to production. Change your build.gradle compile dependency to

`compile 'com.github.codekidX:storage-chooser:e12de59'`
