### ISSUE TITLE
App crash when opening on emulator API 19

### ISSUE THREAD

**Issue by loredan** [codekidX/storage-chooser#65]
```
android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.ListView
   at android.view.LayoutInflater.createView(LayoutInflater.java:621)
   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329)
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693)
   at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
   at android.app.BackStackRecord.run(BackStackRecord.java:684)
   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
   at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5017)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.constructNative(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at android.view.LayoutInflater.createView(LayoutInflater.java:595)
   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
   at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
   at android.app.BackStackRecord.run(BackStackRecord.java:684) 
   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
   at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
   at android.os.Handler.handleCallback(Handler.java:733) 
   at android.os.Handler.dispatchMessage(Handler.java:95) 
   at android.os.Looper.loop(Looper.java:136) 
   at android.app.ActivityThread.main(ActivityThread.java:5017) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:515) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0800c3 a=-1 r=0x7f0800c3}
   at android.content.res.Resources.loadDrawable(Resources.java:2073)
   at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
   at android.widget.AbsListView.<init>(AbsListView.java:785)
   at android.widget.ListView.<init>(ListView.java:146)
   at android.widget.ListView.<init>(ListView.java:142)
   at java.lang.reflect.Constructor.constructNative(Native Method) 
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
   at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
   at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
   at android.app.BackStackRecord.run(BackStackRecord.java:684) 
   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
   at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
   at android.os.Handler.handleCallback(Handler.java:733) 
   at android.os.Handler.dispatchMessage(Handler.java:95) 
   at android.os.Looper.loop(Looper.java:136) 
   at android.app.ActivityThread.main(ActivityThread.java:5017) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:515) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
   at dalvik.system.NativeStart.main(Native Method) 
```

That happens when I open chooser like this:

```java
StorageChooser testChooser = new StorageChooser.Builder()
                .withActivity(getActivity())
                .withFragmentManager(getActivity().getFragmentManager())
                .skipOverview(true, getContext().getSharedPreferences("default", Context.MODE_PRIVATE).getString(PREFERENCE_TESTS_FOLDER, null))
                .filter(StorageChooser.FileType.DOCS)
                .allowCustomPath(true)
                .setType(FILE_PICKER)
                .disableMultiSelect()
                .build();
```

My guess is it has something to do with `custom_storage_list.xml`, which contains this `ListView`

```xml
<ListView
            android:id="@+id/storage_list_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_above="@id/select_button"
            android:layout_below="@id/custom_path_header"
            android:divider="@null"
            android:listSelector="@drawable/ripple"
            android:longClickable="true" />
```

`ripple.xml` is in `drawable-v21` folder and contains `<ripple>` tag, which appeared in API 21. I'm going to try and fix it myself now

**Comment by loredan** [comment]
Oh. Had not noticed that it's already been fixed in master. Closing
