### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0800a0 a=-1 r=0x7f0800a0}

### ISSUE THREAD

**Issue by mikedg1** [codekidX/storage-chooser#74]
I get a crash with the following stack trace  after choosing the root dir to start, when using the pickers on an API Level 19 emulator. 

using 2.0.3
com.github.codekidX:storage-chooser:2.0.3

        StorageChooser chooser = new StorageChooser.Builder()
                .withActivity(activity)
                .withFragmentManager(activity.getFragmentManager())
                .allowCustomPath(true)
                //.allowCustomPath(false) //Works but obviously doesn't let us pick a subdirectory
                .setType(StorageChooser.DIRECTORY_CHOOSER) 
                .build();

        chooser.show();

Setting AllowCustomPath(false) allows us to pick a top level directory without a crash, but then we can't pick a subdir.

Seems fine on API 25, 27.
Doesn't crash on 16, but I run into an issue where I run into issue #62 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.samples1, PID: 2187
                  android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
                      at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329)
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693)
                      at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                      at android.app.BackStackRecord.run(BackStackRecord.java:684)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
                      at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0800a0 a=-1 r=0x7f0800a0}
                      at android.content.res.Resources.loadDrawable(Resources.java:2073)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                      at android.widget.AbsListView.<init>(AbsListView.java:785)
                      at android.widget.ListView.<init>(ListView.java:146)
                      at android.widget.ListView.<init>(ListView.java:142)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:670) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:695) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.getLayout(SecondaryChooserFragment.java:329) 
                      at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.onCreateDialog(SecondaryChooserFragment.java:693) 
                      at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by mikedg1** [comment]
This appears to be related to the ripple.xml, from drawables-v21. The ripple tag is not available on devices < 21 but no alternative XML file is given for lower API levels. One solution is to place a basic color ripple.xml selector in drawable.

**Comment by codekidX** [comment]
I already fixed it, can you compile and use this hash version `com.github.codekidX:storage-chooser:541f3aa` until I draft an official 2.0.4 release.

Thank you, let me know if it works after compiling the above version.

**Comment by pzienowicz** [comment]
Hi @codekidX,

When are you going to release 2.0.4?

**Comment by codekidX** [comment]
Hi @pzienowicz , the release will be today !

**Comment by pzienowicz** [comment]
And where is that release?

**Comment by segler-alex** [comment]
I need that too. Did you manage to fix it?
