### ISSUE TITLE
press title back button will cause FC if "shouldResumeSession" set to true.

### ISSUE THREAD

**Issue by zoularry** [codekidX/storage-chooser#76]
Step to reproduce:
1, select a sdcard path (secondary storage, not internal storage).
2, go into a folder, and press back button on top left of toolbar.
3, crash and got following errors.

NOTE: no crash issue, if go into internal storage OR shouldResumeSession set to false.
-------------------
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.colure.app.scan, PID: 23097
                                                                     java.lang.StringIndexOutOfBoundsException: length=18; index=-1
                                                                         at java.lang.String.substring(String.java:1926)
                                                                         at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.populateList(SecondaryChooserFragment.java:617)
                                                                         at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.performBackAction(SecondaryChooserFragment.java:282)
                                                                         at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.access$1700(SecondaryChooserFragment.java:55)
                                                                         at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$7.onClick(SecondaryChooserFragment.java:181)
                                                                         at android.view.View.performClick(View.java:6213)
                                                                         at android.view.View$PerformClick.run(View.java:23645)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by codekidX** [comment]
Hi, this is same as #79 . Would you mind sharing the path in which it crashed ?

 A workaround is applied and will be released in 2.0.4.
