### ISSUE TITLE
StringIndexOutOfBoundsException hit in SecondaryChooserFragment.java

### ISSUE THREAD

**Issue by brarcher** [codekidX/storage-chooser#79]
Using release v2.0.3 I'm seeing a StringIndexOutOfBoundsException exception in a bug report on Google Play for the [Video Transcoder](https://github.com/brarcher/video-transcoder) application. Logs are not available, only the backtrace:

```
java.lang.StringIndexOutOfBoundsException: 
  at java.lang.String.substring (String.java:1975)
  at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.performBackAction (SecondaryChooserFragment.java:279)
  at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.access$1700 (SecondaryChooserFragment.java:55)
  at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$7.onClick (SecondaryChooserFragment.java:181)
  at android.view.View.performClick (View.java:6256)
  at android.view.View$PerformClick.run (View.java:24701)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:251)
  at android.app.ActivityThread.main (ActivityThread.java:6563)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```

The dialog is being created with the [following](https://github.com/brarcher/video-transcoder/blob/e5473b9b0682c16935fb7f869c3a9c5de856aa9a/app/src/main/java/protect/videotranscoder/activity/MainActivity.java#L352):

```
        final StorageChooser fileChooser = new StorageChooser.Builder()
                .withActivity(MainActivity.this)
                .withFragmentManager(getFragmentManager())
                .allowCustomPath(true)
                .setType(StorageChooser.FILE_PICKER)
                .disableMultiSelect()
                .customFilter(extensions)
                .build();
```

The device where this crash occurred was a Sony Xperia XZ1 (G8341), 4096MB RAM, Android 8.0.

Looking at the [location](https://github.com/codekidX/storage-chooser/blob/master/storagechooser/src/main/java/com/codekidlabs/storagechooser/fragments/SecondaryChooserFragment.java#L279) of the substring() which is failing, could it be that theSelectedPath is empty? I think that adding the skipOverview(true) option would avoid the crash, but might make navigation a little more difficult.

**Comment by ryust** [comment]
I get a similar error on a Samsung with Android 7: 

Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=18; index=-1
       at java.lang.String.substring(String.java:1926)
       at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.populateList(SecondaryChooserFragment.java:617)
       at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.performBackAction(SecondaryChooserFragment.java:282)
       at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment.access$1700(SecondaryChooserFragment.java:55)
       at com.codekidlabs.storagechooser.fragments.SecondaryChooserFragment$7.onClick(SecondaryChooserFragment.java:181)
       at android.view.View.performClick(View.java:6213)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by codekidX** [comment]
Hi @brarcher you got the root of the problem right. But the main issue is that `theSelectedPath` can never be empty since at the start of the SecondaryChooser `mBundlePath` is set as `theSelectedPath` and also the ending point of SecondaryChooser. I need to reproduce this issue perfectly for a path which makes it empty and find out the issue until then this check will avoid the error.

Thanks for reporting this issue @ryust and detailed logs and explanation @brarcher !
